### ISSUE TITLE
FW altitude control overshoot

### ISSUE THREAD

**Issue by jinchengde** [PX4/PX4-Autopilot#10495]
FW altitude change, there is overshoot control
![image](https://user-images.githubusercontent.com/5361334/45616312-9f4e2600-baa1-11e8-905a-d2a777287d56.png)

Looking at the pitch control, that is good for setpoint
![image](https://user-images.githubusercontent.com/5361334/45616361-cad11080-baa1-11e8-9a06-07bacbc0ccd5.png)

the log attach is 
[Flight Review](https://logs.px4.io/plot_app?log=ba6fc1bf-ef2a-4bd0-b357-7db23e39c1f4)

and also discuss in
 [DroneCode Discussion](http://discuss.px4.io/t/fw-overshoot-when-changing-altitude/2382)

**Comment by Antiheavy** [comment]
@RomanBapst @dagar I thought this was a know problem with FW altitude control?  We were able to reduce the overshoot effect slightly by adjusting the TECS tuning, but the pronounced overshoot is still there every time we have a large altitude change.

Here is one of our random flight logs as a reference:
https://review.px4.io/plot_app?log=7c1cf5af-38f4-4f05-8924-8a26f7ac16ac

**Comment by jinchengde** [comment]
@RomanBapst @dagar 
I also test in SITL gazebo plane and it also have overshoot during automatic takeoff, here is the video for you reference
[SITL Gazebo Plane](https://youtu.be/U3nGcOyFCQw)

**Comment by dagar** [comment]
@priseborough any suggestions?

**Comment by priseborough** [comment]
The input shaping applied to the  height and height rate demand inside the TECS _update_height_setpoint function

https://github.com/PX4/ecl/blob/master/tecs/tecs.cpp#L250-L257

can be improved by making the time constant of LPF able to be explicitly set via a parameter. To eliminate overshoot this cannot be much less than the TECS time constant FW_T_TIME_CONST. 

This will need to be done in conjunction with other changes to avoid steady state errors during constant rate climb and descent manouevres, rather than rely on the user adjusting a FW_T_HRATE_FF parameter. 

I will come up with some changes this week.

**Comment by tubeme** [comment]
@priseborough Look at what we came upon while tuning the hrate_ff gain.

In 1.8 we see much better response but still the same behavior on manual control.

https://github.com/PX4/Firmware/issues/8941#issuecomment-371755785

**Comment by priseborough** [comment]
I've done some Matlab simulation work on an alternative algorithm for the input shaping. It works for ramps and steps, noting that with step inputs, any use of a predictor or integrator term to eliminate height error must result in overshoot as neither TECS or the input shaping filter have future knowledge of when the ramp will level off and the vehicle dynamics cannot perform the infinite acceleration required to do so without overshoot.

Step Demand Example

<img width="532" alt="screen shot 2018-10-16 at 4 22 41 pm" src="https://user-images.githubusercontent.com/3596952/46994431-23a6ce00-d160-11e8-9fc1-423faa9ea26b.png">

Ramp Demand Example

<img width="508" alt="screen shot 2018-10-16 at 4 26 46 pm" src="https://user-images.githubusercontent.com/3596952/46994467-4afd9b00-d160-11e8-8418-25622452eb91.png">

Ramp Demand Example - Integrator used to eliminate height offset

<img width="513" alt="screen shot 2018-10-16 at 4 28 06 pm" src="https://user-images.githubusercontent.com/3596952/46994513-7bddd000-d160-11e8-855c-e2805819f53b.png">

The only way we are going to be able to track ramp inputs without height offsets and overshoot is to incorporate move some responsibility for input shaping in the waypoint logic so that TECS is not asked to perform the physically impossible task of tracking a height profile with non continuous first derivative whilst maintaining zero steady state tracking error.

Matlab source code attached:

[height_demand_shaping.m.txt](https://github.com/PX4/Firmware/files/2481539/height_demand_shaping.m.txt)

**Comment by LorenzMeier** [comment]
@bresch Could you please contribute here? It sounds like we should try to do what we’re doing for multicopter as well for TECS here.

**Comment by priseborough** [comment]
It is also worth noting that lag free tracking of a time varying hight input is most important during approach and flare. At other times in flight, eg climbing or descending between waypoints, some lag is normally not an issue. Other autopilot projects using the TECS algorithm work around this by applying the feed-forward correction during landing approach only. This would be an effective short term solution.

**Comment by bresch** [comment]
@priseborough I wrote a library to generate a time-optimal, jerk limited (bang-bang) trajectory based on desired velocity for multicopter velocity control mode (see the [PR](https://github.com/PX4/Firmware/pull/10696)). Position or velocity can be used as the input of the controller and one or several derivative(s) can be used as feedforwards. We could use the same for FW manual control: the input is the desired velocity, based on the sticks.
![vel_traj_graph](https://user-images.githubusercontent.com/14822839/47025066-27881f80-d163-11e8-98e6-3f1d7163482e.png)

I'm planning to do the same for multicopter waypoint navigation (like it's usually done for pick-and-place industrial robots). This could be used to generate a smooth altitude trajectory + feedforwards for TECS in auto mode; do you think it could be a correct solution?

![time-optimal_position-based_trajectory](https://user-images.githubusercontent.com/14822839/47025197-4981a200-d163-11e8-9ba2-bb757f8e925a.png)

**Comment by dagar** [comment]
> neither TECS or the input shaping filter have future knowledge of when the ramp will level off

In an old PR that was never merged I moved the navigator altitude ramp handling into the FW position controller. https://github.com/PX4/Firmware/pull/8883

**Comment by bys1123** [comment]
Is #10746 fix this? @bresch

**Comment by bresch** [comment]
@bys1123 Nope, the PR was for multicopter navigation only but the trajectory generator is in a library and could be reused here. 
However, as Paul demonstrated, a simple 2nd order critically damped input filter should fix the issue. If we don't need to have strict requirements on the maximum amplitude of the derivatives, I would just go with that filter.

**Comment by Antiheavy** [comment]
>  as Paul demonstrated, a simple 2nd order critically damped input filter should fix the issue. If we don't need to have strict requirements on the maximum amplitude of the derivatives, I would just go with that filter.

curious, is anyone working on this already for fixed wing?

**Comment by julianoes** [comment]
@RomanBapst @sfuhrer is this something that could get testing and brought in at some point?

**Comment by julianoes** [comment]
@logindiamant your question seems off topic. Please create a new issue with more detail or ask a question in discuss.px4.io.

**Comment by logindiamant** [comment]
People, who discussed this main issue publish Thrust value in logs... So, question is on topic, @julianoes

**Comment by julianoes** [comment]
Aha sorry @logindiamant. It comes from:
https://github.com/PX4/flight_review/blob/bb39d190b91bb29b5bd43997e26e31976f6b87be/plot_app/configured_plots.py#L331-L333
and therefore:
https://github.com/PX4/Firmware/blob/f9a5c91f8cc5f74ce8d2a0425f7b76d7af65a0a8/msg/actuator_controls.msg#L15

So it's `actuator_controls_0[3]`.

**Comment by logindiamant** [comment]
Ooo, many thanks, @julianoes!!!
I created UAV model on nonlinear differential equations with input {roll, pitch, yawrate and thrust}, and just want to verify it on SITL and real fly UAVs. We plan to fuse model in our visual-inertial odometer

**Comment by bresch** [comment]
fixed by https://github.com/PX4/PX4-Autopilot/pull/18498
