### ISSUE TITLE
`wqueue_test` currently broken`

### ISSUE THREAD

**Issue by julianoes** [PX4/PX4-Autopilot#11028]
When I look at the output of `make tests` I see:
```
wqueue_test: command not found
```

So presumably this test is not actually running right now. Therefore, two things need to be fixed:
1. wqueue_tests needs to be compiled so it can be run.
2. A test should fail if a command is not found (`set -e`?).

**Comment by dagar** [comment]
If I was going to spend time here I think adding a bit more structure would help. Something that registers the tests and executes all of them. Then we could push each test into its corresponding module/driver, and slightly untangle `systemcmds/tests`.

Instead of `px4_add_module` we could have an alternate `px4_add_test` that registers the test and generates a simple script that runs all of them sequentially, catches failures, and reports overall success. That same mechanism should work in sitl and on actual hardware allowing us to drop `ROMFS/px4fmu_test`.

**Comment by julianoes** [comment]
Still relevant.

**Comment by julianoes** [comment]
I feel like this is no longer relevant.
