### ISSUE TITLE
Trajectory generating for VTOL in auto mode

### ISSUE THREAD

**Issue by moreba1** [PX4/PX4-Autopilot#16202]
In some log I see local position setpoint during FW mode such as this log:
https://review.px4.io/plot_app?log=28240df7-4d86-44e0-ba4c-8a442cf9ef1e
![image](https://user-images.githubusercontent.com/14200369/99262517-56d25480-2833-11eb-98a1-32e2c0a6c0fc.png)

but I can not find local continuous position setpoint in my flight logs. 
there is not vehicle_local_position_setpoint message in ulog.
did it discontinue?
https://logs.px4.io/plot_app?log=2d83aeba-df82-453e-8011-58d426d5629d
![image](https://user-images.githubusercontent.com/14200369/99262484-4b7f2900-2833-11eb-8422-fd718fc964e3.png)

**Comment by sfuhrer** [comment]
There is no trajectory setpoint in fixed-wing flight, only the coordinates of the waypoints. So what you see in the old plot where it displays a trajectory setpoint plot is just the current estimated position, because some flight task seems to have set the setpoint = current if not otherwise specified. 
So the fix here wouldn't be to again display the trajectory setpoint (because it doesn't exist) but rather have the current position setpoint displayed in the plots. You can raise that on the review side: https://github.com/PX4/flight_review
I would though argue that the existing 2D plot normally gives you all the info you need: 
![image](https://user-images.githubusercontent.com/26798987/104960122-e7fcad80-59d3-11eb-8ca2-1ac990531a37.png)
