### ISSUE TITLE
Error: the git tag 'f33b118dfb' does not match the expected format.

### ISSUE THREAD

**Issue by daydayupcg137** [PX4/PX4-Autopilot#16262]
Hello,when I "make px4_fmu-v3_default",the error is:

Error: the git tag 'f33b118dfb' does not match the expected format.

The expected format is 'v<PX4 version>[-<custom version>]'
  <PX4 version>: v<major>.<minor>.<patch>[-rc<rc>|-beta<beta>]
  <custom version>: <major>.<minor>.<patch>
Examples:
  v1.9.0rc3 (deprecated)
  v1.9.0-rc3 (preferred)
  v1.9.0-beta1
  v1.9.0-1.0.0
See also https://dev.px4.io/master/en/setup/building_px4.html#firmware_version

**Comment by antonio-sc66** [comment]
Hi, I've seen your other issue #16248. I think the problem is related to your custom firmware as the official one is working. Your fork only has a branch (v1.10-master) and no tags.

The following link explains how you should use tags: https://dev.px4.io/master/en/setup/building_px4.html#firmware-version--git-tags, "These are extracted at build time from the active git tag for your repo tree. The git tag should be formatted as <PX4-version>-<vendor-version> (e.g. the tag in the image above was set to v1.8.1-2.22.1)."

You have to create a tag using the indicated format. If you're working with the v1.10 you can create something like v1.10-0.1.0.
