### ISSUE TITLE
VTOL can not leave loiter in wind 

### ISSUE THREAD

**Issue by moreba1** [PX4/PX4-Autopilot#16438]
Hello

In the SITL test with the gazebo, VTOL could not leave the loiter. this error disappears when we duplicate the L1 Period but in the low L1 period exists.
px4 version: 1.11

log:

https://review.px4.io/plot_app?log=5057cec3-fb7c-4a26-866f-20d3ec035747

**Comment by LorenzMeier** [comment]
You have hit the bank (roll) angle limit: https://review.px4.io/plot_app?log=5057cec3-fb7c-4a26-866f-20d3ec035747#Nav-Roll-Angle

In order to fly at these wind speeds you will need to choose a bigger loiter circle or increase the maximum roll angle (FW_R_LIM). It defaults to 50 degrees, which would have allowed you to stay on course.
