### ISSUE TITLE
compass loss causes unsafe maneuvers

### ISSUE THREAD

**Issue by obicons** [PX4/PX4-Autopilot#17192]
**Describe the bug**
During the landing sequence, a compass failure leads to a position loss and the vehicle jerks violently. Tested on recent commit. 

**To Reproduce**
1. Takeoff
2. Land
3. While landing, fail every compass instance

**Expected behavior**
The vehicle to proceed through the landing sequence.

**Log Files and Screenshots**
https://logs.px4.io/plot_app?log=b9da48e7-9b6a-4a87-a9b0-4d1ffb8d4e26

**Drone (please complete the following information):**
SITL Gazebo Iris

**Additional context**
N/A

**Comment by bresch** [comment]
There are a few strange things that would require further investigations:
- The mag data already stops before takeoff (are you sure you only stopped it during landing?)
- The GNSS vel/pos fusion only seem to start after the mag data stopped
- When the GNSS fusion resets, it has a huge value (was the origin incorrect?)
- The position setpoint isn't exactly adjusted during the reset. It could be a race condition because it looks like the EKF selector switches at the same time.
![DeepinScreenshot_select-area_20210322143347](https://user-images.githubusercontent.com/14822839/111997738-a0051e80-8b1b-11eb-8854-b7c283586ba0.png)

**Comment by priseborough** [comment]
The issue in this log is not compass loss, it is an invalid GPS message that results in the EKF resetting it's position to a 0 lat,lon.
