### ISSUE TITLE
Drone keeps rising with offboard mode over UART

### ISSUE THREAD

**Issue by ashwinlele** [PX4/PX4-Autopilot#17617]
I am trying to use FMUK66 with PX4 1.11.3 and jetson nano as a companion computer for autonomous operations. The companion computer is connected through the UART port to the FMU. I take off in manual mode and switch to position mode when in the air. The drone then starts holding its position using optical flow (px4flow and lidarLite-v3)

I then enable a code that streams MAVLink messages to the drone by remotely accessing the companion computer. After the code starts streaming messages instructing the drone to move with speeds [vx,vy,vz] = [0,0,0] to check if the drone holds the position. QGroundControl says that offboard mode is enabled. But instead of hovering, the drone starts rising while reasonably holding the x and y coordinates. 

I do not understand what command is making it rise when I have explicitly made all velocities zero. The message is given below and is taken from: https://dronekit-python.readthedocs.io/en/latest/guide/copter/guided_mode.html

msg = vehicle.message_factory.set_position_target_local_ned_encode(
        0,       # time_boot_ms (not used)
        0, 0,    # target system, target component
        mavutil.mavlink.MAV_FRAME_BODY_FRD, # frame
        0b0000111111000111, # type_mask (only speeds enabled)
        0, 0, 0, # x, y, z positions (not used)
        velocity_x, velocity_y, velocity_z, # x, y, z velocity in m/s
        0, 0, 0, # x, y, z acceleration (not supported yet, ignored in GCS_Mavlink)
        0, 0)    # yaw, yaw_rate (not supported yet, ignored in GCS_Mavlink)

Thanks so much in advance!

**Comment by Jaeyoung-Lim** [comment]
@ashwinlele If you are only commanding zero velocity, the vehicle will eventually drift, depending on how well the vehicle is tuned to track velocity(Imagine you have very small velocity tracking errors, it will eventually diverge).

Since you are not commanding any position setpoints, the vehicle is simply trying to make the velocity zero. Therefore you would need to create a feedback loop that actively controls altitude if you want the vehicle to stay in one place
