### ISSUE TITLE
After getting error message "Critical navigation failure! Check sensor calibration",position and velocity validity do not recover even if EKF fusion is good 

### ISSUE THREAD

**Issue by JohnSmithDoc** [PX4/PX4-Autopilot#17836]
Hi,I am using px4v1.11 version firmware.I found that if I got "Critical navigation failure! Check sensor calibration"emergency warning in 30 seconds after taking off, the following flags became false but no longer become true even if lpos.xy_valid and lpos.v_xy_valid flag is true.

status_flags.condition_global_position_valid = false;
status_flags.condition_local_position_valid = false;
status_flags.condition_local_velocity_valid = false; 

is this a issue?

I scale some flags in the flightplot:

![image](https://user-images.githubusercontent.com/61374881/124219087-2f17ce80-db2e-11eb-8909-8be06f8bfe3e.png)

![image](https://user-images.githubusercontent.com/61374881/124219121-3ccd5400-db2e-11eb-8187-c719d7e739c5.png)

**Comment by bernhardpg** [comment]
I remember we got the same error message a while back. In our case, it turned out to be electromagnetic interference messing with the compass. Could be worth taking a look at your magnetometer readings!

**Comment by JohnSmithDoc** [comment]
Thank you for your help @bernhardpg 

The reason for this error message is clear to me. It's because the visual_odometry data is bad in 30s after taking off, which caused the three flags:**condition_global_position_valid, condition _local_position_valid and condition_local_velocity_valid** to be false:

![image](https://user-images.githubusercontent.com/61374881/124350141-78971500-dc25-11eb-8a60-0fea2464da73.png)

I also have GPS on my flight controller.The flight controller can still rely on GPS data after vision data stopped.Which is clear in the picture below.The EKF fusion is good after using GPS data. The flags : **vehicle_local_position_0.xy_valid and vehicle_local_position_0.v_xy_valid** are true all the time.

![image](https://user-images.githubusercontent.com/61374881/124349423-76cb5280-dc21-11eb-9144-1c4d4e1a81d2.png)

My question is not about the reason of getting that error message.My question is that why the three flags :**condition_global_position_valid, condition _local_position_valid and condition_local_velocity_valid**  did not recover to true after the EKf fusion became good.

Is that a logical bug or is there any logic to this situation?

**Comment by HHHHHCS** [comment]
I have the same trouble, this is my maibox

**Comment by bresch** [comment]
@JohnSmithDoc It's because when such a failure is detected within the first 30 seconds after takeoff, the local position estimate was considered as faulty. This status cannot be reverted in `v1.11`. See:
 https://github.com/PX4/PX4-Autopilot/blob/21c82a48146fb8afc5a56263a5da21300ba3137e/src/modules/commander/Commander.cpp#L4129-L4130).

With the new yaw emergency estimator and other robustness improvements, we reworked that check to be able to pass again if the EKF recovers.
See: https://github.com/PX4/PX4-Autopilot/pull/16821 and especially 
https://github.com/PX4/PX4-Autopilot/blob/f2ae8ae81466b54cc725c07aa8467991bf74c541/src/modules/commander/Commander.cpp#L3844
This is now in `v1.12`.

**Comment by JohnSmithDoc** [comment]
@bresch Got it,thanks!
