### ISSUE TITLE
MAVSDK Python Odom "translate_to_rpc" error

### ISSUE THREAD

**Issue by farhangnaderi** [PX4/PX4-Autopilot#18154]
**Describe the bug**

While trying to send Odom info to PX4 my script is closed with the error attached as a screenshot.
As @julianoes recommended it might be a bug I opened this issue. 

**To Reproduce**
1. Start SITL with master checked out.
2. Run a script like this : https://gist.github.com/farhangnaderi/d137f8a24023bc4370f54f890132754e

**Expected behavior**
After connection to the drone the script is terminated 

**Log Files and Screenshots**

![image](https://user-images.githubusercontent.com/46557204/131009806-a0553a99-42fb-486b-a7bf-d0282966edf9.png)

**Drone (please complete the following information):**
- Describe the type of drone: SITL

**Additional context**
- N/A

**Comment by julianoes** [comment]
Thanks for the steps to reproduce this @farhangnaderi.
The issue was that the covariance matrix was not set correctly.

If you look at the docs for [Odometry](http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/mocap.html#mavsdk.mocap.Odometry) and [Covariance](http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/mocap.html#mavsdk.mocap.Covariance) you see:

> Covariance type. Row-major representation of a 6x6 cross-covariance matrix upper right triangle. Needs to be 21 entries or 1 entry with NaN if unknown.

So the `pose_covariance` needs to be:
```
    pose_covariance = mocap.Covariance([0.01] * 21)
```
which is an array length 21 with 0.01 each. Or you set it to what makes sense for your input.

**Comment by farhangnaderi** [comment]
Was suspicious I had missed a step. Thanks a lot.
