### ISSUE TITLE
Rover does not move in SITL Gazebo due to missing mixers

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/PX4-Autopilot#19233]
**Describe the bug**
When running Rover SITL, the model is not able to move. This is the reason recently CI testing for rovers have been reliably failing. 

```
Gazebo multi-robot simulator, version 9.19.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 129.132.39.158
file not found
ERROR [mixer_module] mixer reset unavailable, not using static mixers
ERROR [mixer] can't load mixer file: skip
ERROR [mixer] failed to load mixer
ERROR  [init] Failed loading mixer: skip
INFO  [init] setting PWM_AUX_OUT none

```

It seems like rover was configured to use control allocation in https://github.com/PX4/PX4-Autopilot/pull/18776, but now the vehicle is unable to move in SITl Gazebo

@sfuhrer @bkueng Any ideas how to fix this?

**To Reproduce**
1. Run `make px4_sitl gazebo_rover`

**Comment by oceanusxiv** [comment]
@Jaeyoung-Lim lol just my luck I was messing around with this today and hit this immediately. It looks like what's happening is that during the control allocation changes, there was a misunderstanding on how the SITL rover is configured. See

https://github.com/PX4/PX4-Autopilot/blob/cc6c6c3b8cb56f79eb6bb09d8d4bc7535a30b184/ROMFS/px4fmu_common/init.d-posix/airframes/1060_rover#L37

which treats the two rear wheel throttles as a 0...1 as opposed to -1...1 which was how the original mixer file configured it. Since rover motors can reverse the original config was correct. Fortunately I think all that's needed is to change the two entries in that file from `101` to `201` like the steering servo configs, that should help.

I am still seeing weird position control behavior even after this though, namely the steering keeps oscillating, but I'm not sure if it's related.
