### ISSUE TITLE
Unclear intention of sign function

### ISSUE THREAD

**Issue by tstastny** [PX4/PX4-Autopilot#19361]
**Describe the bug**
https://github.com/PX4/PX4-Autopilot/blob/c86d5769eaa719d5a3898060bf81b074d36228be/src/lib/matrix/matrix/helper_functions.hpp#L155-L159

Not sure if bug - but no documentation on intention so wanted to clarify. If one runs the following on the matrix lib sign function:
```
#include <iostream>
#include <cfloat>

float signOf(float val) {
    return float((FLT_EPSILON < val) - (val < FLT_EPSILON));
}

int main() {

    std::cout << signOf(-1.0f) << std::endl;
    std::cout << signOf(-FLT_EPSILON) << std::endl;
    std::cout << signOf(0.0f) << std::endl;
    std::cout << signOf(FLT_EPSILON) << std::endl;
    std::cout << signOf(1.0f) << std::endl;

    return 0;
}
```
the output is:
```
-1
-1
-1
0
1
```
**Expected behavior**
`sign` functions either have a positive or negative definition for a value input equal to zero (so that means the only two outputs possible are -1 or 1), **or** they have a 0 criteria, either exactly =0, or a deadzone.
1. is it intended that the sign function should return zero if within a "deadzone"?
2. if so, shouldn't 0 also return 0? e.g. `(T(FLT_EPSILON) < val) - (val < -T(FLT_EPSILON))`

Regardless of the intention, after this discussion we should update the method documentation.

**Comment by MaEtUgR** [comment]
> is it intended that the sign function should return zero if within a "deadzone"?

It is, for the definition that cannot return zero there's the function `signNoZero()`:
https://github.com/PX4/PX4-Autopilot/blob/c86d5769eaa719d5a3898060bf81b074d36228be/src/lib/mathlib/math/Functions.hpp#L50-L55

They are in different places because of the historical dependencies of the matrix and ecl submodule dependencies. I'd vote for putting them in the same place outside of the matrix library and making the matrix library depend on e.g. math::functions explicitly in CMake.

> if so, shouldn't 0 also return 0?

Totally, let me check 👀 

> we should update the method documentation

I completely agree, I can add that.

**Comment by MaEtUgR** [comment]
@tstastny I suggest this https://github.com/PX4/PX4-Autopilot/pull/19366 and then I'll make a pr to move the functions.
