### ISSUE TITLE
Discussion on changing of Home Position coordinates in-air

### ISSUE THREAD

**Issue by junwoo091400** [PX4/PX4-Autopilot#19448]
## Overview
I have came across multiple cases where a 'home position' coordinate would change during flight like this:

imestamp,lat,lon,alt,x,y,z,yaw,valid_alt,valid_hpos,valid_lpos,manual_home
539783884,**47.35659097864523,8.519027041192425,424.23907,-0.04685232,-1.5034404,-6.491614,2.8605902**,1,1,1,0
1288817192,**47.35660062025529,8.519080194755471,422.52423,1.0252461,2.5004663,-4.7767744,1.11605**,1,1,1,0

So the latitude and longitude of the home position has shifted. And, as I have checked separately, the origin of the local position coordinate (vehicle_local_position.ref_lat, ref_lon, ref_alt) didn't change.

![GPS_Offset_Analysis](https://user-images.githubusercontent.com/23277211/162166790-05088153-13d8-4fe2-9e48-61868f7ddd1f.png)

For example in this plot, you can view the shift in home position starting at the tip of the arrow, then shifting up-right direction mid-flight.

## Setup
I am testing a quadcopter using this branch : #19260 

## Log file
https://logs.px4.io/plot_app?log=4990bb12-f988-4320-a415-41f8ceb43b90

## Additional context
This was discussed briefly in the dev call yesterday : https://discuss.px4.io/t/px4-dev-call-april-06-2022/26787

**Comment by bresch** [comment]
The home position isn't changing mid-flight, there is one home position set on takeoff and one after disarming. You see it changing during flight with PlotJuggler because the value of the closest point is shown (first half of the flight, the left one, 2nd half, the right one).
![DeepinScreenshot_select-area_20220407142614](https://user-images.githubusercontent.com/14822839/162198219-1deb3209-bb06-49b0-90f4-56fae76d211b.png)
