### ISSUE TITLE
What's the difference between autopilot and ardupilot?i want to build a car(UAV),have some problem

### ISSUE THREAD

**Issue by zouzhe1** [PX4/PX4-Autopilot#19648]
I have a pixhawk fmv5,I want to build a car.
I want to achieve, drive slowly on the road, then encounter moving obstacles, wait, and then complete the target route. I plan to install 4 ultrasonic waves (front and rear, left and right), 2 lidars (front and rear), and cameras (for later visual recognition) and GPS.

What's the difference between autopilot and ardupilot?

Later, I need to connect pixhawk to ROS for visual recognition. I think autopilot is better than ardupilot, but I look at Google and others say that ardupilot's program is more advanced? Which is their better support for ROS和rover?

Thanks!

**Comment by zouzhe1** [comment]
Moreover, I want to know the relationship between the keywords [pixhawk], [Px4], [autopilot], [ardupilot]. I don't know

**Comment by cbjornram** [comment]
Hi zouzhe1,

This is not the place for these kinds of questions since this area of GitHub should mainly be used to report issues with the flight controller firmware called PX4. For more questions regarding PX4 and its echo system (such as Mavlink, QGroundControl, and Pixhawk) I would refer to the forums: https://discuss.px4.io/.

But to clear up your confusion I will try to give you a short summery that hopefully can answer your questions:

- **Autopilot**: An autopilot is a system that automatically controls a vehicle. It is not a product or a brand, but a name for all kinds of different systems that automatically (or partially automatically) controls vehicles. The [Wikipedia article](https://en.wikipedia.org/wiki/Autopilot#:~:text=An%20autopilot%20is%20a%20system,do%20not%20replace%20human%20operators.) about it explains more in depth.
- **Flight controller**: A flight controller is the main computer (the brain) of drones (multicopters and fixed wings), but today also boats and cars (usually called rovers). It is some kind of hardware (such as Pixhawk) running a flight controller firmware (such as PX4, Ardupilot, Betaflight, or other alternatives).
- **Flight controller firmware**: This is the software running on the flight controller hardware. Here are all the settings, functions, features, and inner workings of how the vehicle is controlled.
- **Ardupilot**: Ardupilot is a flight controller firmware. It has different versions for different kind of vehicles. ArduPlane for fixed wing and VTOL (Vertical Take Off Landing), ArduCopter for multicopters and helicopters, ArduRover for rovers (cars) and boats.
- **PX4**: PX4 is exactly like Ardupilot, a flight controller firmware. They do very similar things and you would use one or the other, not both for the same vehicle. PX4 (in difference from Ardupilot) includes all vehicle types in the same firmware. There are many other differences between them and I would suggest you search the internet for more details about these differences and what fits your use case best. You will get different answers about which is best depending on where you ask, and if you ask here (which is a place for PX4 issues), most probably the answer will be that PX4 is best for ROS applications. If you ask in an Ardupilot forum, the answer will probably be that Ardupilot is best for ROS applications.
- **Pixhawk**: Pixhawk is two things: 
  - A family of hardware flight controller hardwares. Popular choices of Pixhawk flight controllers includes [Pixhawk 4](http://www.holybro.com/product/pixhawk-4/) and [Pixhawk 5X](http://www.holybro.com/product/pixhawk-5x/). There are also older versions that still works great today. There are also a lot of other kinds of flight controllers that supports both PX4 and Ardupilot that are not Pixhawks. For more info, check out the lists at [PX4 Autopilot Hardwares](https://docs.px4.io/master/en/flight_controller/) and [Ardupilot Autopilot Hardwares](https://ardupilot.org/copter/docs/common-autopilots.html).
  - A hardware design standard for how flight controllers can (and should) be designed to fully support PX4. For example Pixhawk 4 and Pixhawk 5X are both built using different versions of the Pixhawk design standard. For more info, check out [PX4 Standards](https://pixhawk.org/standards/).
- Companion Computer: You didn't ask about this, but since your use case will require one I include it anyway. A Companion Computer is a separate computer mounted on the vehicle that is connected to the flight controller. The flight controller usually has limited resources in terms of processing power, and to do heavy processing of data (such as visual recognition) a companion computer normally is used. The companion computer does the heavy processing work and then sends control information to the flight controller.

I hope this have helped you a little bit. Please close this issue and use the forum, or the PX4 Slack (which is usually more development focused) for more questions. You have the links to them on the [PX4 Support Page](https://docs.px4.io/master/en/contribute/support.html). If you would like to get in contact with the Ardupilot community instead you can find there links at [Ardupilot Communication Channels](https://ardupilot.org/copter/docs/common-contact-us.html).

All the best,
Christoffer

**Comment by zouzhe1** [comment]
@cbjornram Thank you for your reply. I have purchased cuav V5 +, Jetson nano, Intel d435 camera, 2D ladir, and am looking forward to receiving the express.

**Comment by cbjornram** [comment]
Good luck! And boring side note: Please remember to close this issue.

Cheers!

**Comment by Muammer06** [comment]
hello, can you update about your rover?
Which one you selected as a Autopilot and what's the status right now?
