### ISSUE TITLE
Failsafe Enabled: No Local Position drone crashes 

### ISSUE THREAD

**Issue by airsimdevdd** [PX4/PX4-Autopilot#19682]
my drone crashed sideways after showing failsafe enabled no local position  can anyone explain , this  here is my attached photos @Jaeyoung-Lim 
![bokeh_plot(4)](https://user-images.githubusercontent.com/77828768/169466667-efe94d1a-e22c-4f23-926b-f6efb77ef90f.png)
![bokeh_plot(5)](https://user-images.githubusercontent.com/77828768/169467066-10bdb6d0-f789-4d4f-ae15-3d63b6fc4396.png)
![bokeh_plot(6)](https://user-images.githubusercontent.com/77828768/169467069-fd795827-42ad-4dd1-b284-077c7bd38ab7.png)
![bokeh_plot(7)](https://user-images.githubusercontent.com/77828768/169467075-0dedbffd-d2cc-46aa-9724-f9708d27dbba.png)
![Screenshot from 2022-05-20 11-54-54](https://user-images.githubusercontent.com/77828768/169467235-f077b645-1441-477f-afb3-7aef089a29cf.png)

1c.png)

**Comment by mcsauder** [comment]
Hi @airsimdevdd , could you post a link to the full log here?

**Comment by airsimdevdd** [comment]
for some reasons i can't  post full log here

**Comment by bresch** [comment]
All the plots you share suggest an issue with the magnetic field measured by the magnetometer: The norm of the magnetic field seems correlated with the thrust and its norm is way too large (almost 10Gs while the earth mag field is ~0.4-0.6Gs). I guess you already suspected the mag since you shared those plots.
You probably need to move the magnetometer further away from cables, batteries and other components that can radiate a large magnetic field.

**Comment by bresch** [comment]
Since it isn't a software issue, I would suggest to continue on the forum and in PX4 slack.
