### ISSUE TITLE
command denied during calibration: 241

### ISSUE THREAD

**Issue by tomzzz989** [PX4/PX4-Autopilot#19863]
This problem occurred when I calibrated the magnetic compass. My version is 1.11.0, as shown in the figure
![mmexport1656868584777](https://user-images.githubusercontent.com/66825833/177050340-84a8efaf-e50c-4cc4-98db-5cdec27ef742.png)
![mmexport1656868578392](https://user-images.githubusercontent.com/66825833/177050344-22e3723d-c047-42a7-b73a-5df88579d79a.png)

**Comment by dagar** [comment]
Can you please try v1.13.0 or current PX4 main branch?

**Comment by tomzzz989** [comment]
I tried 1.13.0, which will give me another error about SD card. On my other plane, 1.11.0 works normally, so I chose 1.11.0
![mmexport1656895661060](https://user-images.githubusercontent.com/66825833/177063920-fc8b64a4-9750-4a30-afb0-ecbf2e17b568.png)

**Comment by dagar** [comment]
I don't know what the issue is with v1.11.0, but it may have to do with matching QGC version. It definitely wasn't normal to get a "command denied during calibration" error at the time or we would have fixed it. We don't have the resources to maintain old releases, but we can do point releases on v1.13 if there are actual issues.

To silence the "Missing FMU SD card" error you can set `COM_ARM_SDCARD 0` or insert a usable SD card.

**Comment by tomzzz989** [comment]
Anyway, thank you for taking the time to think about it。

**Comment by tomzzz989** [comment]
I changed the version to 1.10.1 after the problem was solved.
