### ISSUE TITLE
VehicleCommandAck in ROS2

### ISSUE THREAD

**Issue by kribe48** [PX4/PX4-Autopilot#21430]
## Describe the bug
I am not able to make the microdds_client publish the VehicleCommandAck uORB message, such that it can be accessed via ROS2. The steps works for the BatteryStatus message, but not for the VehicleCommandAck message.

## To Reproduce
1. Add the following lines to dds_topics.yaml in the microdds_client module:   
- topic: /fmu/out/vehicle_command_ack
   type: px4_msgs::msg::VehicleCommandAck
3. Launch any PX4_SITL vehicle (e.g. via make px4_sitl gz_x500)
4. Connect a Micro-XRCE-Agent as described in https://docs.px4.io/main/en/ros/ros2_comm.html#setup-xrce-dds-agent-client
5. Check what type of publishers that are created by the microdds_client 

## Expected behavior
The topic "/fmu/out/vechilce_command_ack" to be visible as a ROS2 topic

## Log Files and Screenshots
![image](https://user-images.githubusercontent.com/20855764/230040456-3ce57040-6aa3-48db-8d0c-2ad800a5af7f.png)

**Comment by beniaminopozzan** [comment]
The client current behavior is that the dds publishers are created only after the first message is received by the client itself.
VehicleCommandAck is rarely published, that's why it is not immediately processed. Just open QGC, or send any VehicleCommand message AFTER the client has started and you will see the Ack being added to the list of publishers
