### ISSUE TITLE
Choosing Pixhawk Controller

### ISSUE THREAD

**Issue by tuananh0606-tech** [PX4/PX4-Autopilot#23273]
### Describe problem solved by the proposed feature

I want to control a quadcopter when one or two actuators are broken, and I am looking at the pixhawk 6c controller and the pixhawk 4 controller, which pixhawk controller should I choose? Thanks everyone.

### Describe your preferred solution

Find the controller you need

### Describe possible alternatives

Pixhawk 4 or pixhawk 6c

**Comment by federicociresola** [comment]
I think it is always better to buy the last version of Pixhawk because the idea is that the end date of support is futher away. 
The Pixhawk 4 is old than the 6* version in addition the price is very similar between 4 and 6C 
but the 6C is more powerful than 4

I leve here a little comparison among two board ( [Pixhawk 4 ](https://holybro.com/collections/autopilot-flight-controllers/products/pixhawk-4) , [Pixhawk 6C](https://holybro.com/collections/autopilot-flight-controllers/products/pixhawk-6c) )
| Specification       | Pixhawk 4                                              | Pixhawk 6C                                         |
|---------------------|---------------------------------------------------------|----------------------------------------------------|
| **Main FMU Processor** | STM32F765 - 32 Bit Arm® Cortex®-M7, 216MHz, 2MB memory, 512KB RAM | STM32H743 - 32 Bit Arm® Cortex®-M7, 480MHz, 2MB memory, 1MB SRAM |
| **IO Processor**    | STM32F103 - 32 Bit Arm® Cortex®-M3, 72MHz, 64KB SRAM (Current) <br> STM32F100 - 32 Bit Arm® Cortex®-M3, 24MHz, 8KB SRAM (Discontinued) | STM32F103 - 32 Bit Arm® Cortex®-M3, 72MHz, 64KB SRAM |
| **On-board Sensors**| Accel/Gyro: ICM-20689 <br> Accel/Gyro: BMI055/ICM-20602 <br> Mag: IST8310 <br> Barometer: MS5611 | Accel/Gyro: ICM-42688-P <br> Accel/Gyro: BMI055 <br> Mag: IST8310 <br> Barometer: MS5611 |
| **Power Module Output** | 4.9~5.5V                                              | N/A                                                |
| **Max Input Voltage**  | 6V                                                    | 6V                                                 |
| **Max Current Sensing** | 120A                                                 | N/A                                                |
| **USB Power Input**    | 4.75~5.25V                                            | 4.75~5.25V                                         |
| **Servo Rail Input**   | 0~36V                                                 | 0~36V                                              |
| **Telem1 Max Output Current Limiter** | N/A                                                    | 1.5A                                               |
| **All Other Port Combined Output Current Limiter** | N/A                                                    | 1.5A                                               |
| **Dimensions**       | 44x84x12mm                                             | 84.8x44x12.4mm                                     |
| **Weight**           | 33.3g (Plastic Case) <br> 49g (Aluminum Case)         | 34.6g (Plastic Case) <br> 59.3g (Aluminum Case)   |
